# Generated by Django 5.0.6 on 2024-08-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_comments_comment_rename_reviews_review"),
        ("my_site", "__first__"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="author",
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="my_site.author",
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="review",
            name="project",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="posts"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(to="my_site.tag"),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
