# Generated by Django 5.0.6 on 2024-08-17 17:10

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_project_author_alter_post_author_and_more"),
    ]

    operations = [
        
    ]