# Generated by Django 5.0.6 on 2024-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_auto_20240817_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="images/posts"),
        ),
    ]
