# Generated by Django 5.0.6 on 2024-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_comment_comment_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
