# Generated by Django 5.0.6 on 2024-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="avatar",
            field=models.ImageField(upload_to="images/authors"),
        ),
    ]
